org: smrnjeet222
app: pricetracker
service: pricetracker-cron


provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-1'
  timeout: 900
  lambdaHashingVersion: 20201221
functions:
  track:
    handler: handler.track
    events:
      - schedule: rate(2 minutes)